### ISSUE TITLE
setup scripts need to be tested in a clean environment

### ISSUE THREAD

**Issue by mslucke99** [mslucke99/document-reader#8]

**Comment by DanielRunningen** [comment]
When I tested it, the `wget` address was slightly off. I removed the `?dl=1` and the `tar` command was successful. `pyaudio` wasn't in `requirements.txt` but was in the `README.md` in the `barcode` directory and should probably be included in the `apt install` command instead as `python3-pyaudio`. 

I also mentioned some package suggestions in #9 and uploaded an example using a Pipfile and Pipfile.lock in [a separate branch](https://github.com/mslucke99/document-reader).
